import type { MeetingItemProps } from '@features/congregation/field_service_meetings/meeting_item';

const unsortedMeetings: MeetingItemProps[] = [
  {
    id: 1,
    time: new Date('2025-08-02T09:30:00'),
    type: 'joint',
    conductor: 'Luciano Campos',
    assistant: 'Luis Coelho',
    materials: 'Brochura Ame as Pessoas - Lição 8 - Imite Jesus - Pontos 3-5',
  },
  {
    id: 2,
    time: new Date('2025-08-03T09:30:00'),
    type: 'joint',
    conductor: 'Ernesto',
    assistant: 'João Silvestre',
    materials: 'Brochura Leitura e Ensino - Lição 8 - Ensine com Ilustrações',
  },
  {
    id: 3,
    time: new Date('2025-08-06T09:30:00'),
    type: 'joint',
    conductor: 'José Pinto',
    assistant: 'N/A',
    materials:
      'Brochura Leitura e Ensino - Lição 19 - Toque o coração das Pessoas (Na Pregação)',
  },
  {
    id: 11,
    time: new Date('2025-08-09T09:30:00'),
    type: 'group',
    group: 'Esteveira',
    conductor: 'Josías António',
    location: 'Natanael Fortunato',
    materials: 'Brochura Ame as Pessoas - Lição 8 - Imite Jesus - Pontos 3-5',
  },
  {
    id: 10,
    time: new Date('2025-08-09T10:00:00'),
    type: 'group',
    group: 'Passos Esteves',
    conductor: 'José Pinto',
    location: 'José Pinto',
    materials: 'Brochura Ame as Pessoas - Lição 8 - Imite Jesus - Pontos 3-5',
  },
  {
    id: 12,
    time: new Date('2025-08-09T10:00:00'),
    type: 'group',
    group: 'Bairro da Camara',
    conductor: 'Armindo Ramalho',
    location: 'Manuel Ramalho',
    materials: 'Brochura Ame as Pessoas - Lição 8 - Imite Jesus - Pontos 3-5',
  },
  {
    id: 13,
    time: new Date('2025-08-09T10:00:00'),
    type: 'group',
    group: 'Grupo Salão 1',
    conductor: 'Samuel Pereira',
    location: 'Salão do Reino',
    materials: 'Brochura Ame as Pessoas - Lição 8 - Imite Jesus - Pontos 3-5',
  },
  {
    id: 14,
    time: new Date('2025-08-09T10:00:00'),
    type: 'group',
    group: 'Grupo Salão 2',
    conductor: 'Fábio Ferreira',
    location: 'Salão do Reino',
    materials: 'Brochura Ame as Pessoas - Lição 8 - Imite Jesus - Pontos 3-5',
  },
  {
    id: 4,
    time: new Date('2025-08-10T09:30:00'),
    type: 'joint',
    conductor: 'Fernando Silvestre',
    assistant: 'Fábio Ferreira',
    materials:
      'W 21/ Julho - Será que pode ajudar no trabalho de fazer Discípulos? Página 3 - Parágrafo 3-6',
  },
  {
    id: 5,
    time: new Date('2025-08-13T09:30:00'),
    type: 'joint',
    conductor: 'Armindo Ramalho',
    assistant: 'N/A',
    materials: 'Introdução à Palavra de Deus - Pergunta 1 - Quem é Deus?',
  },
  {
    id: 6,
    time: new Date('2025-08-16T09:30:00'),
    type: 'joint',
    conductor: 'Luis Silvestre',
    assistant: 'Gonçalo Coelho',
    materials:
      'W 21/ Julho - O Amor Motiva-nos a fazer discípulos - Página 5 - Parágrafos 7-9',
  },
  {
    id: 7,
    time: new Date('2025-08-20T09:30:00'),
    type: 'joint',
    conductor: 'António José',
    assistant: 'N/A',
    materials:
      'Introdução à Palavra de Deus - Pergunta 18 - Como pode achegar-se a Deus?',
  },
  {
    id: 8,
    time: new Date('2025-08-27T09:30:00'),
    type: 'joint',
    conductor: 'António José',
    assistant: 'N/A',
    materials:
      'Introdução à Palavra de Deus - Pergunta 10 - O que a Bíblia promete para o Futuro?',
  },
  {
    id: 9,
    time: new Date('2025-08-30T09:30:00'),
    type: 'joint',
    conductor: 'António José',
    assistant: 'Ruben Boneco',
    materials: 'Brochura Leitura e Ensino - Lição 4 - Introduza bem os Textos.',
  },
  {
    id: 16,
    time: new Date('2025-08-23T09:30:00'),
    type: 'group',
    group: 'Esteveira',
    conductor: 'António Evangelista',
    location: 'Nataniel Fortunato',
    materials: 'Brochura Leitura e Ensino - Lição 8 - Ensine com Ilustrações',
  },
  {
    id: 15,
    time: new Date('2025-08-23T10:00:00'),
    type: 'group',
    group: 'Passos Esteves',
    conductor: 'Luis Coelho',
    location: 'José Pinto',
    materials: 'Brochura Leitura e Ensino - Lição 8 - Ensine com Ilustrações',
  },
  {
    id: 17,
    time: new Date('2025-08-23T10:00:00'),
    type: 'group',
    group: 'Bairro da Camara',
    conductor: 'Armindo Ramalho',
    location: 'Manuel Ramalho',
    materials: 'Brochura Leitura e Ensino - Lição 8 - Ensine com Ilustrações',
  },
  {
    id: 18,
    time: new Date('2025-08-23T10:00:00'),
    type: 'group',
    group: 'Grupo Salão 1',
    conductor: 'Samuel Pereira',
    location: 'Salão do Reino',
    materials: 'Brochura Leitura e Ensino - Lição 8 - Ensine com Ilustrações',
  },
  {
    id: 19,
    time: new Date('2025-08-23T10:00:00'),
    type: 'group',
    group: 'Grupo Salão 2',
    conductor: 'Ernesto Franco',
    location: 'Salão do Reino',
    materials: 'Brochura Leitura e Ensino - Lição 8 - Ensine com Ilustrações',
  },
  {
    id: 20,
    time: new Date('2025-08-23T10:00:00'),
    type: 'zoom',
    conductor: 'Armindo Ramalho',
    materials: 'Brochura Leitura e Ensino - Lição 8 - Ensine com Ilustrações',
  },
];

export const mockMeetings: MeetingItemProps[] = unsortedMeetings.sort(
  (a, b) => a.time.getTime() - b.time.getTime()
);
